# Generated by Django 5.2.2 on 2025-06-07 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypKolorystyczny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(choices=[('spring_light', 'Jasna Wiosna'), ('spring_warm', 'Ciepła Wiosna'), ('spring_clear', 'Czysta Wiosna'), ('summer_light', 'Jasne Lato'), ('summer_cool', 'Chłodne Lato'), ('summer_soft', 'Miękkie Lato'), ('autumn_soft', 'Miękka Jesień'), ('autumn_warm', 'Ciepła Jesień'), ('autumn_deep', 'Głęboka Jesień'), ('winter_cool', 'Chłodna Zima'), ('winter_clear', 'Czysta Zima'), ('winter_deep', 'Głęboka Zima')], max_length=50, unique=True)),
                ('opis', models.TextField()),
                ('dominujaca_tonacja', models.CharField(max_length=20)),
                ('poziom_kontrastu', models.CharField(max_length=20)),
                ('nasycenie', models.CharField(max_length=20)),
                ('kolory_podstawowe', models.JSONField(default=list)),
                ('kolory_unikane', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Typ Kolorystyczny',
                'verbose_name_plural': 'Typy Kolorystyczne',
            },
        ),
        migrations.CreateModel(
            name='Analiza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('processing', 'Przetwarzanie'), ('completed', 'Zakończona'), ('error', 'Błąd')], default='pending', max_length=20)),
                ('zdjecie_nadgarstka', models.ImageField(upload_to='analizy/nadgarstki/')),
                ('zdjecie_oczu', models.ImageField(upload_to='analizy/oczy/')),
                ('zdjecie_wlosow', models.ImageField(upload_to='analizy/wlosy/')),
                ('tonacja_skory', models.CharField(blank=True, max_length=20)),
                ('kontrast_poziom', models.IntegerField(blank=True, null=True)),
                ('nasycenie_poziom', models.IntegerField(blank=True, null=True)),
                ('kolory_skory', models.JSONField(default=list)),
                ('kolory_oczu', models.JSONField(default=list)),
                ('kolory_wlosow', models.JSONField(default=list)),
                ('notatki', models.TextField(blank=True)),
                ('pewnosc_wyniku', models.FloatField(blank=True, null=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analizy', to=settings.AUTH_USER_MODEL)),
                ('typ_kolorystyczny', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='color_analyzer.typkolorystyczny')),
            ],
            options={
                'verbose_name': 'Analiza',
                'verbose_name_plural': 'Analizy',
                'ordering': ['-data_utworzenia'],
            },
        ),
        migrations.CreateModel(
            name='PlikAnalizy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_pliku', models.CharField(max_length=255)),
                ('plik', models.FileField(upload_to='analizy/pliki/')),
                ('rozmiar', models.IntegerField()),
                ('typ_mime', models.CharField(max_length=100)),
                ('data_uploadu', models.DateTimeField(default=django.utils.timezone.now)),
                ('analiza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pliki', to='color_analyzer.analiza')),
            ],
            options={
                'verbose_name': 'Plik Analizy',
                'verbose_name_plural': 'Pliki Analiz',
            },
        ),
        migrations.CreateModel(
            name='ProfilUzytkownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiek', models.IntegerField(blank=True, null=True)),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna'), ('N', 'Nie podano')], default='N', max_length=1)),
                ('data_rejestracji', models.DateTimeField(default=django.utils.timezone.now)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ulubiony_typ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='color_analyzer.typkolorystyczny')),
            ],
            options={
                'verbose_name': 'Profil Użytkownika',
                'verbose_name_plural': 'Profile Użytkowników',
            },
        ),
    ]
