# Generated by Django 4.2.7 on 2025-06-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typkolorystyczny',
            name='nazwa_publiczna',
            field=models.CharField(default='', max_length=100),
        ),
    ]
